
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/som # basic ?? ??? ??
    username: root
    password: sb813792!! # 1234 ????? ?? ???? ????? ???.
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

