server:
  port: 8001
spring:
  application:
    name: admin
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/som
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #create
    show-sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: isky1990@naver.com
    password: 1q2w3e4r!!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  redis:
    host: team6-redis-ro.uoizyu.ng.0001.apn2.cache.amazonaws.com
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}

jwt:
  expiration: 30
  secretKey: mysecret


logging:
  level:
    root: info
