server:
  port: 8002
spring:
  application:
    name: board

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/som
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587 # 2
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: ${AWS_RDS_HOST}
    port: 6379

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#    enabled: true
#  instance:
#    instance-id: ${spring.application.name}:${random.value}


jwt:
  expiration: 30
  secretKey: mysecret