server:
  port: 8003
spring:
  application:
    name: batch
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/som
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update #update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  redis:
    host: ${AWS_RDS_HOST}
    port: 6379
#eureka:
#  client:
#    service-url:
#      defaultZone : http://127.0.0.1:8761/eureka
#    enabled: true
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
